services:
    shuwee_config.parameter_admin:
        class: Wanjee\Shuwee\ConfigBundle\Admin\ParameterAdmin
        parent: shuwee_admin.admin_abstract
        tags:
          -  { name: shuwee.admin, alias: parameter }


    shuwee_config.manager:
        class: Wanjee\Shuwee\ConfigBundle\Utils\ParameterManager
        arguments: [@doctrine.orm.entity_manager]

    # Twig
    shuwee_config.parameter_twig_extension:
        class: Wanjee\Shuwee\ConfigBundle\Twig\ParameterExtension
        arguments: [@shuwee_config.manager]
        public: false
        tags:
            - { name: twig.extension }
